### ISSUE TITLE
Fix broken since 4.2 (maybe 4.1)

### ISSUE THREAD

**Issue by toto621-linux** [nhok0169/Anime-Game-Remap#21]
I just tried raiden boss fight today and the fix isn't working anymore, it need to be updated. Last time it was working for me was 4.0, didn't tried with 4.1.

**Comment by Alex-Au1** [comment]
Have you installed the **latest version** of the fix?

The fix has undergone a **HUGE CHANGE** since 4.1... :stuck_out_tongue_winking_eye: 
<br>

If you do not want to always go on Github and worry about **whether you have the latest version**, I recommend you to run **by CMD** as a **[Python Module](https://pypi.org/project/FixRaidenBoss2/)**:

## Step 1
Install the latest release by typing on CMD:
```bash
python -m pip install -U FixRaidenBoss2
```

## Step 2
run this line on CMD in the Raiden mod folder
```bash
python -m FixRaidenBoss2
```
<br>

More info at [README](https://github.com/nhok0169/Fix-Raiden-Boss/tree/nhok0169/Fix-Raiden-Boss%202.0%20(for%20all%20user%20)) and [EXAMPLES](https://github.com/nhok0169/Fix-Raiden-Boss/tree/nhok0169/Examples)


## All Version Releases:
https://github.com/Alex-Au1/Fix-Raiden-Boss/releases

<br>
<br>

**IF THE NEWEST CHANGES DOES NOT WORK, PLEASE MAKE A NEW ISSUE WITH THE SCREENSHOT THE ERROR LOG**

**Comment by Alex-Au1** [comment]
@nhok0169 

in my opinion, this issue can be closed as an **invalid bug** (I don't have permissions to close it)

**Comment by toto621-linux** [comment]
Yes i'm using latest version of the python script, it do not produce error but it do not work, the boss model is still completely broken after running the fix.

![WIP-01](https://github.com/nhok0169/Fix-Raiden-Boss/assets/88256778/f9c0d10b-7e67-4722-a288-7a83c978d756)

@Alex-Au1 I do not open issue for nothing so please refrain yourself, thank you.

**Comment by Alex-Au1** [comment]
Did you press F10 to reload the mods?

Is this a specific individual mod on the site? If it is, send the link, so I can test it out.

Otherwise, send the generated .ini file

**Comment by toto621-linux** [comment]
Of course I pressed F10, even rebooted the game.

Here is the mod used : https://gamebanana.com/mods/437248

**Comment by Alex-Au1** [comment]
interesting,
send your .ini file

not sure if it may be build issue (maybe with different OS or version of GIMI)
cause im able to get the mod work on my computer

![image](https://github.com/nhok0169/Fix-Raiden-Boss/assets/45087631/8aa9c8bb-78d7-4c3e-8bc9-97d8496554f2)

**Comment by toto621-linux** [comment]
Well, I use latest publicly available GIMi (v7) so if it work for you then there is something that bug it out on my side for sure. I will have to check mods one by one until I found the culpit.

Here is the ini : [RaidenShogun.zip](https://github.com/nhok0169/Fix-Raiden-Boss/files/13325004/RaidenShogun.zip)

**Comment by Alex-Au1** [comment]
Not sure if this has anything but when comparing your .ini to mine, it looks like you are using the **white fur**'s .ini file instead of the **black fur**'s .ini file based on our different draw values

![image](https://github.com/nhok0169/Fix-Raiden-Boss/assets/45087631/ab15a812-b352-4f52-b526-da1062dcff4b)

**Comment by Alex-Au1** [comment]
Also, looks like your .ini did not run the 4.1 fix script

```.ini
[TextureOverride41FixVertexLimitRaise0]
hash = 29bb54cb
```

**Comment by toto621-linux** [comment]
I sent you the original ini from lewdlad by mistake.

Holly molly that was it, I don't know why but the draw potision was borked. The weird part is that the mod still worked (boss fight excluded of course)

Sorry for all this it was in my end that the issue occured all along, stupid me, issue closed, I will hit my head on the wall for being so dumb.
